before_deploy:
  - stack exec dhall-to-json <<< "./ci/bintray.dhall {date = \"$(date '+%Y-%m-%d')\", tag = \"${TRAVIS_TAG}\", tarFile = \"${TAR_FILE}\"}" > ci/bintray.json
  - tar --create --file ${TAR_FILE} --directory bin --gzip purcel

before_install:
  - ci/install-stack.sh --os ${TRAVIS_OS_NAME} --verbose

cache:
  directories:
    - ${HOME}/.local/bin
    - .stack-root
    - .stack-work
  timeout: 1000

deploy:
  - file: ci/bintray.json
    key: ${BINTRAY_API_KEY}
    on:
      repo: joneshf/purcel
      tags: true
    provider: bintray
    skip_cleanup: true
    user: joneshf

env:
  global:
    - PATH=/usr/local/opt/coreutils/libexec/gnubin:${PATH}
    - STACK_ROOT=${TRAVIS_BUILD_DIR}/.stack-root
    - TAR_FILE=purcel-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz

install:
  - stack setup
  - stack build dhall-json

language: c

os:
  - linux
  - osx

sudo: false

script:
  - stack build --copy-bins --local-bin-path bin --no-run-tests --test
  - stack build --test
