author: Hardy Jones
category: Web
copyright: 2018 Hardy Jones
homepage: https://github.com/joneshf/purcel#readme
license: BSD3
maintainer: jones3.hardy@gmail.com
name: purcel
version: 0.1.0.0

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - ViewPatterns

dependencies:
  - base == 4.11.1.0
  - dhall == 1.13.1
  - rio == 0.1.2.0

executables:
  purcel:
    dependencies:
      - optparse-applicative == 0.14.2.0
      - purcel
    main: Main.hs
    source-dirs: src

extra-source-files:
  - README.md
  - purcel/*
  - snapshot/*
  - types/*

ghc-options:
  - -Wall
  - -Werror
  - -Widentities
  - -Wimplicit-prelude
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-exported-signatures
  - -Wmissing-home-modules
  - -Wmissing-local-signatures
  - -Wmonomorphism-restriction
  - -Wredundant-constraints

library:
  source-dirs: lib

tests:
  purescript:
    dependencies:
      - purcel
    main: Main.hs
    source-dirs: test
